ampleforth/spot

.gitignore, spot-contracts/tasks/ganache.sh, spot-contracts/tasks/goeril.sh, spot-contracts/tasks/helpers.ts, spot-contracts/tasks/mainnet.sh, spot-contracts/tasks/ops/index.ts, spot-contracts/tasks/ops/perp.ts, spot-contracts/tasks/ops/perp_rollover.ts
New helper script does to calculate the amount of ampl required to rollover the entire SPOT supply. 
It also generates a `Batch.json` file which can be uploaded into Gnosis safe to automatically populate the transaction values. 
(PSA: do not trust the script, always double check before submitting any transaction)
```
yarn hardhat --network goerli ops:preview_tx:trancheAndRollover \
--wallet-address [WALLET] \
--router-address 0x5e902bdCC408550b4BD612678bE2d57677664Dc9 \
--perp-address 0x95014Bc18F82a98CFAA3253fbD3184125A01f848
```
```
---------------------------------------------------------------
Rollover preview
balanceAvailable 56004638.766259293
collateralUsed 2207.073339441
rolloverAmt 1101.890069575
---------------------------------------------------------------
collateralToken …
```
=> Helper script

.gitignore, spot-contracts/tasks/mainnet.sh, spot-contracts/tasks/ops/perp_rollover.ts
CLI utility to preview mature and immature redemption based on wallet's balances
=> Added task to preview redeem

spot-contracts/contracts/BondIssuer.sol, spot-contracts/contracts/_interfaces/IBondIssuer.sol, spot-contracts/test/BondIssuer.ts
- updated issuer book keeping to keep track of active bond indices
- Added helper to execute `mature` on active bonds when they are up for maturity
=> Issuer update v1.1.0

spot-contracts/contracts/PerpetualTranche.sol, spot-contracts/contracts/_utils/BondHelpers.sol, spot-contracts/contracts/test/BondHelpersTester.sol, spot-contracts/contracts/vaults/RolloverVault.sol, spot-contracts/test/_utils/BondHelpers.ts
- Users deposit AMPL for vault notes
- Vault "deploys" ampl by tranching and performing rollover, it "recovers" AMPL by redeeming mature tranches
- On redemption users get a slice of all the assets held by the vault
At any given time the vault could hold, the underlying asset (deposit asset AMPL), the earned asset (SPOT) and the deployed assets (tranches).
=> Rollover vault

spot-contracts/contracts/_interfaces/IVault.sol, spot-contracts/contracts/vaults/RolloverVault.sol, spot-contracts/test/vaults/RolloverVault_deploy.ts
* Added deployment count limit to prevent large loops which might run out of gas
=> Deployment count cap

spot-contracts/contracts/_interfaces/IVault.sol, spot-contracts/contracts/vaults/RolloverVault.sol, spot-contracts/test/vaults/RolloverVault.ts, spot-contracts/test/vaults/RolloverVault_deploy.ts, spot-contracts/test/vaults/RolloverVault_deposit_redeem.ts
* Enforcing a minimum amount to be deployed
* Guards against potential grief from dust tokens which could trigger `recoverAndRedeploy`
* Contract owner can control `minDeploymentAmt` param
=> Min deployment amount enforcement

spot-contracts/contracts/_utils/BondHelpers.sol, spot-contracts/contracts/vaults/RolloverVault.sol, spot-contracts/test/vaults/RolloverVault_recover.ts
**Gas numbers before**
```
·-------------------------------------------------------|---------------------------|-------------|-----------------------------·
|                 Solc version: 0.8.19                  ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 30000000 gas  │
························································|···························|·············|······························
|  Methods                                              ·              122 gwei/gas               ·       1847.70 usd/eth       │
·····················|··································|·············|·············|·············|···············|··············
|  Contract          ·  Method                          ·  Min        ·  Max        ·  Avg        ·  # calls      ·  usd …
```
=> Recovery optimization

spot-contracts/contracts/_utils/BondHelpers.sol, spot-contracts/test/_utils/BondHelpers.ts, spot-contracts/test/helpers.ts
The `computeRedeemableTrancheAmounts` should round the balances down to a number divisible by the tranche ratio. 
For example, if the tranche balances are "10, 15, 7.461048491123254231" the previous implementation returned "2.984419396449301692, 4.476629094673952538, 7.461048491123254231".
However, this is not the right redemption ratio, which is expected to be precisely divisible. 
https://github.com/buttonwood-protocol/tranche/blob/main/contracts/BondController.sol#L229
The proposed change rounds down to achieve amounts are consistent with the expected tranche ratio. 
We get -> "2.984419396449301600, 4.476629094673952400, 7.461048491123254000"
=> Fixed rounding issue with recovery

spot-contracts/contracts/PerpetualTranche.sol, spot-contracts/contracts/RouterV1.sol, spot-contracts/contracts/_interfaces/IPerpetualTranche.sol, spot-contracts/contracts/vaults/RolloverVault.sol, spot-contracts/test/vaults/RolloverVault_recover.ts
- As part of the batch recovery, we first redeem the earned perp tokens for the underlying tranches and then continue with the existing flow.
- Updated perp methods "deposit", "redeem" and "rollover" to return data about the operation.
=> Added perp redemption to vault recovery flow

spot-contracts/contracts/FeePolicy.sol, spot-contracts/contracts/PerpetualTranche.sol, spot-contracts/contracts/RolloverVault.sol, spot-contracts/contracts/RouterV2.sol, spot-contracts/contracts/_interfaces/ProtocolErrors.sol, spot-contracts/contracts/_utils/BondHelpers.sol, spot-contracts/test/FeePolicy.ts, spot-contracts/test/RouterV2.ts, spot-contracts/test/_utils/HelpersTester.ts, spot-contracts/test/helpers.ts, spot-contracts/test/perp/PerpetualTranche.ts, spot-contracts/test/perp/PerpetualTranche_deposit.ts, spot-contracts/test/perp/PerpetualTranche_redeem.ts, spot-contracts/test/perp/PerpetualTranche_rollover.ts, spot-contracts/test/rollover-vault/RolloverVault.ts, spot-contracts/test/rollover-vault/RolloverVault_deploy.ts, spot-contracts/test/rollover-vault/RolloverVault_deposit_redeem.ts, spot-contracts/test/rollover-vault/RolloverVault_recover.ts, spot-contracts/test/rollover-vault/RolloverVault_swap.ts
Contains changes from comments in [this](https://docs.google.com/spreadsheets/d/1kDIujHNLutL0bXB4bjeFQK9n8RNehZs2lrNqilSzUus/edit#gid=0) sheet (colored in orange). 
Additionally
* Added max reserve length parameter to perp (similar to the vault)
* Updated perp's `getReserveTokensUpForRollover` method to remove `address(0)` and return a smaller array with just the tokens to rollover. It consumes slightly more gas, but lesser data is passed downstream. 
* Enforcing vault's liquidity constraints on both swap functions. (its a cheap check and there could be weird cases where the swapPerpsForUnderlying fn decreases the available vault liquidity when it does not have the matching juniors) 
* Fixed bug in the router contract, which first has to issue the deposit bond before querying it.
=> Audit fixes - 2nd pass

LICENSE, spot-contracts/contracts/FeePolicy.sol, spot-contracts/test/FeePolicy.ts
* Updated fee policy sigmoid bound to allow for 20% yearly rate
* Updated license
=> V2 final updates

spot-contracts/contracts/BondIssuer.sol
hello
the words were in the incorrect order, so I have revised it to make sense
Br, Elias.
=> fix: BondIssuer.sol

spot-vaults/README.md, spot-vaults/contracts/UsdcSpotManager.sol, spot-vaults/contracts/WethWamplManager.sol, spot-vaults/contracts/_interfaces/IBillBrokerPricingStrategy.sol, spot-vaults/package.json, spot-vaults/tasks/deploy.ts, spot-vaults/tasks/info.ts, spot-vaults/test/UsdcSpotManager.ts, spot-vaults/test/WethWamplManager.ts, yarn.lock
* Fixed couple of minor bugs in the wampl-weth vault manager implementation. 1) Force rebalancing when limit ranges change. 2) Handling invalid oracle data, winding down to inf range. 3) Removing limit ranges completely instead of narrow/wide
* Added a new auto manager for the SPOT-USDC charm vault. (mostly similar to wampl-weth, but adjusts liquidity based on SPOT's deviation from FMV)
=> Charm Vault manager update

spot-vaults/README.md, spot-vaults/contracts/UsdcSpotManager.sol, spot-vaults/tasks/deploy.ts, spot-vaults/tasks/info.ts, spot-vaults/tasks/tools.ts, spot-vaults/test/UsdcSpotManager.ts
Fixed oracle price calculation on spot-usdc manager. We need usd per spot, not the other way around ..
=> Fixed minor issue with spot manager

.github/workflows/nightly.yml, .github/workflows/test.yml, spot-vaults/README.md, spot-vaults/contracts/BillBroker.sol, spot-vaults/contracts/UsdcSpotManager.sol, spot-vaults/contracts/_interfaces/ISpotPricingStrategy.sol, spot-vaults/contracts/_strategies/SpotAppraiser.sol, spot-vaults/contracts/_strategies/SpotCDRPricer.sol, spot-vaults/tasks/deploy.ts, spot-vaults/tasks/info.ts, spot-vaults/test/SpotAppraiser.ts, spot-vaults/test/SpotCDRPricer.ts, spot-vaults/test/UsdcSpotManager.ts
Added a new SPOT pricing strategy for the charm manager. 
The bill broker uses the spot appraiser which has stricter rules around DR and tranche CDRs. However, the AMM pool can use a much simpler pricing strategy.
=> Spot pricer for automanager

spot-vaults/contracts/BillBroker.sol, spot-vaults/hardhat.config.ts, spot-vaults/package.json, spot-vaults/test/BillBroker_deposit_redeem.ts, spot-vaults/test/BillBroker_swap.ts, yarn.lock
1) Added USD,Perp single sided deposit when pool is unbalanced
2) Added events for subgraph indexing
=> Single sided deposit for Billy

spot-contracts/contracts/RolloverVault.sol, spot-contracts/test/rollover-vault/RolloverVault_swap.ts
Skipping liquidity check when swapping from perps to underlying.
Swapping from perps to underlying should almost always increase the vault's liquidity, so we only check if underlying balance doesn't decrease.
=> Swap limit bug fix

spot-contracts/contracts/RolloverVault.sol, spot-contracts/test/rollover-vault/RolloverVault.ts, spot-contracts/test/rollover-vault/RolloverVault_deploy.ts, spot-contracts/test/rollover-vault/RolloverVault_swap.ts
1) Vault's min liquidity constraints are enforced universally before rollover and after swaps
2) The limiting percentage parameter is a percentage of vault's neutral TVL
=> Updated liquidity check condition based on system subscription ratio

spot-vaults/contracts/_utils/AlphaVaultHelpers.sol, spot-vaults/contracts/charm/UsdcSpotManager.sol, spot-vaults/test/UsdcSpotManager.ts
An new alpha vault strategy for spot-usdc which is scalable and can provide deep concentrated liquidity around SPOT's fmv.
=> Scalable usdc-spot univ3 strategy

spot-vaults/contracts/BillBroker.sol, spot-vaults/contracts/_interfaces/errors/CommonErrors.sol, spot-vaults/contracts/_interfaces/types/BillBrokerTypes.sol, spot-vaults/contracts/_test/LineHelpersTester.sol, spot-vaults/contracts/_utils/LineHelpers.sol, spot-vaults/contracts/_utils/MathHelpers.sol, spot-vaults/package.json, spot-vaults/test/BillBroker.ts, spot-vaults/test/BillBroker_deposit_redeem.ts, spot-vaults/test/BillBroker_swap.ts, spot-vaults/test/LineHelpers.ts, yarn.lock
Previously the bill broker swap fee curve was piecewise function with 2 lines. This change makes it a piecewise with 3 lines as shown in the image and now supports negative fees. 
We stored fee percentages as a unsigned fixed-point number with 18 decimals (1e18 = 100% or 1.0) which doesn't support negative fee values. Now we simply covert the existing percentages into a factor by adding 1e18. Under the new scheme:
0% => 1.0 or 1e18
100% => 2.0 or 2e18
-20% => 0.8 or 8e17
=> Bill broker fee curve change

spot-contracts/contracts/FeePolicy.sol, spot-contracts/contracts/_interfaces/ProtocolErrors.sol, spot-contracts/test/FeePolicy.ts
Updated enrichment/debasement fee curve. 
**Motivation:**
The current implementation caps the enrichment rate when dr is high. The side-effect of this is that the vault's effective funding rate (rate vault holders pay to get magnified exposure) reduces. 
When dr = 2, for example the perpTVL:vaultTVL ratio is 1:6 and at dr = 3 its 1:9. Say there's a perp tvl of 1m$. Perp's enrichment would be ~200k at dr = 2 and at dr = 3. However, the vault's effective rate would be 200k/6m ~3.3% when dr =2 and 200k/9m ~2.2% when dr = 3 and so on. So it actually continues to go down. (As shown in the following figure)
Alternatively as dr continues to increase we want the vault's effective funding rate to increase or at least stay constant. This would mean that perp's enrichment rate is unbounded on the …
=> Fee curve update

spot-contracts/contracts/FeePolicy.sol, spot-contracts/package.json, spot-contracts/test/FeePolicy.ts, yarn.lock
The rollover fee computation adjusts the fees based on the vault's subscription ratio.
For example, if the vault's sr = 0.5, it means that at most half of perp can be rolled over. Thus the rollover fees are doubled.
=> Rollover fee curve update

spot-contracts/contracts/FeePolicy.sol, spot-contracts/contracts/RolloverVault.sol, spot-contracts/contracts/RouterV2.sol, spot-contracts/contracts/_interfaces/IFeePolicy.sol, spot-contracts/contracts/_interfaces/IRolloverVault.sol, spot-contracts/contracts/_interfaces/IVault.sol, spot-contracts/contracts/_utils/BondHelpers.sol, spot-contracts/contracts/_utils/ERC20Helpers.sol, spot-contracts/contracts/_utils/TrancheManager.sol, spot-contracts/hardhat.config.ts, spot-contracts/package.json, spot-contracts/test/FeePolicy.ts, spot-contracts/test/RouterV2.ts, spot-contracts/test/perp/PerpetualTranche.ts, spot-contracts/test/perp/PerpetualTranche_deposit.ts, spot-contracts/test/perp/PerpetualTranche_redeem.ts, spot-contracts/test/rollover-vault/RolloverVault.ts, spot-contracts/test/rollover-vault/RolloverVault_deploy.ts, spot-contracts/test/rollover-vault/RolloverVault_deposit_redeem.ts, spot-contracts/test/rollover-vault/RolloverVault_pair_ops.ts, spot-contracts/test/rollover-vault/RolloverVault_rebalance.ts, spot-contracts/test/rollover-vault/RolloverVault_recover.ts, spot-contracts/test/rollover-vault/RolloverVault_swap.ts, yarn.lock
Mint2 & Redeem2 => Ability to mint/redeem spot and stampl as matching pairs.
=> Pair operations

spot-contracts/contracts/FeePolicy.sol, spot-contracts/contracts/PerpetualTranche.sol, spot-contracts/contracts/RolloverVault.sol, spot-contracts/contracts/RouterV2.sol, spot-contracts/contracts/_interfaces/CommonTypes.sol, spot-contracts/contracts/_interfaces/IFeePolicy.sol, spot-contracts/contracts/_interfaces/IPerpetualTranche.sol, spot-contracts/contracts/_interfaces/IRolloverVault.sol, spot-contracts/contracts/_interfaces/IVault.sol, spot-contracts/contracts/_interfaces/ProtocolErrors.sol, spot-contracts/contracts/_utils/BondHelpers.sol, spot-contracts/contracts/_utils/ERC20Helpers.sol, spot-contracts/contracts/_utils/TrancheManager.sol, spot-contracts/hardhat.config.ts, spot-contracts/package.json, spot-contracts/tasks/ops/vaults.ts, spot-contracts/test/FeePolicy.ts, spot-contracts/test/RouterV2.ts, spot-contracts/test/perp/PerpetualTranche.ts, spot-contracts/test/perp/PerpetualTranche_deposit.ts, spot-contracts/test/perp/PerpetualTranche_redeem.ts, spot-contracts/test/perp/PerpetualTranche_rollover.ts, spot-contracts/test/rollover-vault/RolloverVault.ts, spot-contracts/test/rollover-vault/RolloverVault_deploy.ts, spot-contracts/test/rollover-vault/RolloverVault_deposit_redeem.ts, spot-contracts/test/rollover-vault/RolloverVault_pair_ops.ts, spot-contracts/test/rollover-vault/RolloverVault_rebalance.ts, spot-contracts/test/rollover-vault/RolloverVault_recover.ts, spot-contracts/test/rollover-vault/RolloverVault_swap.ts, yarn.lock
1) Perp's mint/burn fees are paid to the vault (by minting/transfering perp tokens)
2) All fees collected during flash swaps go to the vault's balance. (before it was split between perp and the vault)
3) Added owner defined drSoftBounds (similar to bill broker), which determine when flash swap fees transition from constant value to the linearly increasing fee (previously the kink point was dr=1.0).
=> Restructuring perp/vault fees

spot-contracts/contracts/FeePolicy.sol, spot-contracts/contracts/PerpetualTranche.sol, spot-contracts/contracts/RolloverVault.sol, spot-contracts/contracts/_interfaces/CommonTypes.sol, spot-contracts/contracts/_interfaces/IFeePolicy.sol, spot-contracts/contracts/_interfaces/IRolloverVault.sol, spot-contracts/hardhat.config.ts, spot-contracts/tasks/ops/vaults.ts, spot-contracts/test/FeePolicy.ts, spot-contracts/test/RouterV2.ts, spot-contracts/test/perp/PerpetualTranche.ts, spot-contracts/test/perp/PerpetualTranche_deposit.ts, spot-contracts/test/perp/PerpetualTranche_redeem.ts, spot-contracts/test/perp/PerpetualTranche_rollover.ts, spot-contracts/test/rollover-vault/RolloverVault.ts, spot-contracts/test/rollover-vault/RolloverVault_deploy.ts, spot-contracts/test/rollover-vault/RolloverVault_deposit_redeem.ts, spot-contracts/test/rollover-vault/RolloverVault_pair_ops.ts, spot-contracts/test/rollover-vault/RolloverVault_rebalance.ts, spot-contracts/test/rollover-vault/RolloverVault_recover.ts, spot-contracts/test/rollover-vault/RolloverVault_swap.ts
Now the spot system doesn't care about the bond ratios used by the underlying tranches. It balances incentives and fees based on an owner defined vaultTVL : perpTVL target ratio (or system ratio)
=> Removed subscription ratio for a global vault:perp tvl (or system ratio)

spot-contracts/contracts/FeePolicy.sol, spot-contracts/test/FeePolicy.ts
If we think the fees act as brakes, then we should be able to start applying the fees before the system gets out of balance.
So for example, when dr > 1; and dr is decreasing we can start applying fees at 1.05 (ie before we get to 1). Similarly when dr < 1 and dr is increasing, we can start applying fees at 0.95 rather than wait till we get to 1.
=> Fee update
